spring:
    application:
        name: healthcheck-application



server:
    servlet:
        contextPath: /healthcheck
    port: 9000


#Kafka Properties
kafka:
    json-topic: json-topic
    avro-topic: avro-topic
    producer:
        bootstrap-servers: localhost:9092
        client-id: healthcheck-producer
        acks: all
        retries: 3
        batch-size: 16384 
        linger-ms: 1
        buffer-memory: 33554432
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-json-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-avro-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
        schemaregistry-url: http://localhost:8081
        interceptor: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
    consumer:
        bootstrap-servers: localhost:9092
        group-id: healthcheck-group
        auto-offset-reset: earliest
        session-timeout-ms: 30000
        enable-auto-commit: true
        auto-commit-interval-ms: 500
        max-poll-records: 200
        topic-concurrrency:  3
        poll-timeout: 5000
        client-id: healthcheck-consumer
        interceptor: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor



#Swagger details:
swagger:
    api:
        contactEmail:
        contact:
        version:
        description:
        title:
        base:
        package:
